-- migrate:up

INSERT INTO provinces (id, name, department_id) VALUES (1, 'Chachapoyas', 1);
INSERT INTO provinces (id, name, department_id) VALUES (2, 'Bagua ', 1);
INSERT INTO provinces (id, name, department_id) VALUES (3, 'Bongara ', 1);
INSERT INTO provinces (id, name, department_id) VALUES (4, 'Condorcanqui', 1);
INSERT INTO provinces (id, name, department_id) VALUES (5, 'Luya ', 1);
INSERT INTO provinces (id, name, department_id) VALUES (6, 'Rodriguez De Mendo', 1);
INSERT INTO provinces (id, name, department_id) VALUES (7, 'Utcubamba', 1);
INSERT INTO provinces (id, name, department_id) VALUES (8, 'Huaraz', 2);
INSERT INTO provinces (id, name, department_id) VALUES (9, 'Aija', 2);
INSERT INTO provinces (id, name, department_id) VALUES (10, 'Antonio Raymondi', 2);
INSERT INTO provinces (id, name, department_id) VALUES (11, 'Asunción', 2);
INSERT INTO provinces (id, name, department_id) VALUES (12, 'Bolognesi', 2);
INSERT INTO provinces (id, name, department_id) VALUES (13, 'Carhuaz', 2);
INSERT INTO provinces (id, name, department_id) VALUES (14, 'Carlos F. Fitzcarrald', 2);
INSERT INTO provinces (id, name, department_id) VALUES (15, 'Casma ', 2);
INSERT INTO provinces (id, name, department_id) VALUES (16, 'Corongo ', 2);
INSERT INTO provinces (id, name, department_id) VALUES (17, 'Huari', 2);
INSERT INTO provinces (id, name, department_id) VALUES (18, 'Huarmey ', 2);
INSERT INTO provinces (id, name, department_id) VALUES (19, 'Huaylas', 2);
INSERT INTO provinces (id, name, department_id) VALUES (20, 'Mariscal Luzuriaga', 2);
INSERT INTO provinces (id, name, department_id) VALUES (21, 'Ocros ', 2);
INSERT INTO provinces (id, name, department_id) VALUES (22, 'Pallasca ', 2);
INSERT INTO provinces (id, name, department_id) VALUES (23, 'Pomabamba', 2);
INSERT INTO provinces (id, name, department_id) VALUES (24, 'Recuay', 2);
INSERT INTO provinces (id, name, department_id) VALUES (25, 'Santa', 2);
INSERT INTO provinces (id, name, department_id) VALUES (26, 'Sihuas ', 2);
INSERT INTO provinces (id, name, department_id) VALUES (27, 'Yungay', 2);
INSERT INTO provinces (id, name, department_id) VALUES (28, 'Abancay', 3);
INSERT INTO provinces (id, name, department_id) VALUES (29, 'Andahuaylas', 3);
INSERT INTO provinces (id, name, department_id) VALUES (30, 'Antabamba', 3);
INSERT INTO provinces (id, name, department_id) VALUES (31, 'Aymaraes', 3);
INSERT INTO provinces (id, name, department_id) VALUES (32, 'Cotabambas', 3);
INSERT INTO provinces (id, name, department_id) VALUES (33, 'Chincheros', 3);
INSERT INTO provinces (id, name, department_id) VALUES (34, 'Grau', 3);
INSERT INTO provinces (id, name, department_id) VALUES (35, 'Arequipa', 4);
INSERT INTO provinces (id, name, department_id) VALUES (36, 'Camana', 4);
INSERT INTO provinces (id, name, department_id) VALUES (37, 'Caraveli', 4);
INSERT INTO provinces (id, name, department_id) VALUES (38, 'Castilla', 4);
INSERT INTO provinces (id, name, department_id) VALUES (39, 'Caylloma', 4);
INSERT INTO provinces (id, name, department_id) VALUES (40, 'Condesuyos', 4);
INSERT INTO provinces (id, name, department_id) VALUES (41, 'Islay', 4);
INSERT INTO provinces (id, name, department_id) VALUES (42, 'La Union ', 4);
INSERT INTO provinces (id, name, department_id) VALUES (43, 'Huamanga', 5);
INSERT INTO provinces (id, name, department_id) VALUES (44, 'Cangallo ', 5);
INSERT INTO provinces (id, name, department_id) VALUES (45, 'Huanca Sancos', 5);
INSERT INTO provinces (id, name, department_id) VALUES (46, 'Huanta', 5);
INSERT INTO provinces (id, name, department_id) VALUES (47, 'La Mar', 5);
INSERT INTO provinces (id, name, department_id) VALUES (48, 'Lucanas', 5);
INSERT INTO provinces (id, name, department_id) VALUES (49, 'Parinacochas', 5);
INSERT INTO provinces (id, name, department_id) VALUES (50, 'Paucar Del Sara Sara', 5);
INSERT INTO provinces (id, name, department_id) VALUES (51, 'Sucre', 5);
INSERT INTO provinces (id, name, department_id) VALUES (52, 'Victor Fajardo', 5);
INSERT INTO provinces (id, name, department_id) VALUES (53, 'Vilcas Huaman', 5);
INSERT INTO provinces (id, name, department_id) VALUES (54, 'Cajamarca', 6);
INSERT INTO provinces (id, name, department_id) VALUES (55, 'Cajabamba', 6);
INSERT INTO provinces (id, name, department_id) VALUES (56, 'Celendin ', 6);
INSERT INTO provinces (id, name, department_id) VALUES (57, 'Chota ', 6);
INSERT INTO provinces (id, name, department_id) VALUES (58, 'Contumaza ', 6);
INSERT INTO provinces (id, name, department_id) VALUES (59, 'Cutervo ', 6);
INSERT INTO provinces (id, name, department_id) VALUES (60, 'Hualgayoc', 6);
INSERT INTO provinces (id, name, department_id) VALUES (61, 'Jaen', 6);
INSERT INTO provinces (id, name, department_id) VALUES (62, 'San Ignacio', 6);
INSERT INTO provinces (id, name, department_id) VALUES (63, 'San Marcos', 6);
INSERT INTO provinces (id, name, department_id) VALUES (64, 'San Miguel ', 6);
INSERT INTO provinces (id, name, department_id) VALUES (65, 'San Pablo', 6);
INSERT INTO provinces (id, name, department_id) VALUES (66, 'Santa Cruz', 6);
INSERT INTO provinces (id, name, department_id) VALUES (67, 'Callao', 7);
INSERT INTO provinces (id, name, department_id) VALUES (68, 'Cusco ', 8);
INSERT INTO provinces (id, name, department_id) VALUES (69, 'Acomayo ', 8);
INSERT INTO provinces (id, name, department_id) VALUES (70, 'Anta', 8);
INSERT INTO provinces (id, name, department_id) VALUES (71, 'Calca', 8);
INSERT INTO provinces (id, name, department_id) VALUES (72, 'Canas ', 8);
INSERT INTO provinces (id, name, department_id) VALUES (73, 'Canchis', 8);
INSERT INTO provinces (id, name, department_id) VALUES (74, 'Chumbivilcas', 8);
INSERT INTO provinces (id, name, department_id) VALUES (75, 'Espinar', 8);
INSERT INTO provinces (id, name, department_id) VALUES (76, 'La Convencion', 8);
INSERT INTO provinces (id, name, department_id) VALUES (77, 'Paruro ', 8);
INSERT INTO provinces (id, name, department_id) VALUES (78, 'Paucartambo', 8);
INSERT INTO provinces (id, name, department_id) VALUES (79, 'Quispicanchi', 8);
INSERT INTO provinces (id, name, department_id) VALUES (80, 'Urubamba', 8);
INSERT INTO provinces (id, name, department_id) VALUES (81, 'Huancavelica', 9);
INSERT INTO provinces (id, name, department_id) VALUES (82, 'Acobamba ', 9);
INSERT INTO provinces (id, name, department_id) VALUES (83, 'Angaraes ', 9);
INSERT INTO provinces (id, name, department_id) VALUES (84, 'Castrovirreyna', 9);
INSERT INTO provinces (id, name, department_id) VALUES (85, 'Churcampa', 9);
INSERT INTO provinces (id, name, department_id) VALUES (86, 'Huaytara', 9);
INSERT INTO provinces (id, name, department_id) VALUES (87, 'Tayacaja', 9);
INSERT INTO provinces (id, name, department_id) VALUES (88, 'Huanuco ', 10);
INSERT INTO provinces (id, name, department_id) VALUES (89, 'Ambo ', 10);
INSERT INTO provinces (id, name, department_id) VALUES (90, 'Dos De Mayo', 10);
INSERT INTO provinces (id, name, department_id) VALUES (91, 'Huacaybamba', 10);
INSERT INTO provinces (id, name, department_id) VALUES (92, 'Huamalies', 10);
INSERT INTO provinces (id, name, department_id) VALUES (93, 'Leoncio Prado', 10);
INSERT INTO provinces (id, name, department_id) VALUES (94, 'Marañón', 10);
INSERT INTO provinces (id, name, department_id) VALUES (95, 'Pachitea ', 10);
INSERT INTO provinces (id, name, department_id) VALUES (96, 'Puerto Inca ', 10);
INSERT INTO provinces (id, name, department_id) VALUES (97, 'Lauricocha ', 10);
INSERT INTO provinces (id, name, department_id) VALUES (98, 'Yarowilca', 10);
INSERT INTO provinces (id, name, department_id) VALUES (99, 'Ica', 11);
INSERT INTO provinces (id, name, department_id) VALUES (100, 'Chincha', 11);
INSERT INTO provinces (id, name, department_id) VALUES (101, 'Nazca ', 11);
INSERT INTO provinces (id, name, department_id) VALUES (102, 'Palpa  ', 11);
INSERT INTO provinces (id, name, department_id) VALUES (103, 'Pisco ', 11);
INSERT INTO provinces (id, name, department_id) VALUES (104, 'Huancayo', 12);
INSERT INTO provinces (id, name, department_id) VALUES (105, 'Concepcion', 12);
INSERT INTO provinces (id, name, department_id) VALUES (106, 'Chanchamayo', 12);
INSERT INTO provinces (id, name, department_id) VALUES (107, 'Jauja', 12);
INSERT INTO provinces (id, name, department_id) VALUES (108, 'Junin ', 12);
INSERT INTO provinces (id, name, department_id) VALUES (109, 'Satipo ', 12);
INSERT INTO provinces (id, name, department_id) VALUES (110, 'Tarma ', 12);
INSERT INTO provinces (id, name, department_id) VALUES (111, 'Yauli', 12);
INSERT INTO provinces (id, name, department_id) VALUES (112, 'Chupaca', 12);
INSERT INTO provinces (id, name, department_id) VALUES (113, 'Trujillo', 13);
INSERT INTO provinces (id, name, department_id) VALUES (114, 'Ascope', 13);
INSERT INTO provinces (id, name, department_id) VALUES (115, 'Bolivar ', 13);
INSERT INTO provinces (id, name, department_id) VALUES (116, 'Chepen ', 13);
INSERT INTO provinces (id, name, department_id) VALUES (117, 'Julcan ', 13);
INSERT INTO provinces (id, name, department_id) VALUES (118, 'Otuzco ', 13);
INSERT INTO provinces (id, name, department_id) VALUES (119, 'Pacasmayo', 13);
INSERT INTO provinces (id, name, department_id) VALUES (120, 'Pataz', 13);
INSERT INTO provinces (id, name, department_id) VALUES (121, 'Sanchez Carrion', 13);
INSERT INTO provinces (id, name, department_id) VALUES (122, 'Santiago De Chuco', 13);
INSERT INTO provinces (id, name, department_id) VALUES (123, 'Gran Chimu', 13);
INSERT INTO provinces (id, name, department_id) VALUES (124, 'Viru', 13);
INSERT INTO provinces (id, name, department_id) VALUES (125, 'Chiclayo', 14);
INSERT INTO provinces (id, name, department_id) VALUES (126, 'Ferreñafe', 14);
INSERT INTO provinces (id, name, department_id) VALUES (127, 'Lambayeque ', 14);
INSERT INTO provinces (id, name, department_id) VALUES (128, 'Lima', 15);
INSERT INTO provinces (id, name, department_id) VALUES (129, 'Barranca ', 15);
INSERT INTO provinces (id, name, department_id) VALUES (130, 'Cajatambo', 15);
INSERT INTO provinces (id, name, department_id) VALUES (131, 'Canta', 15);
INSERT INTO provinces (id, name, department_id) VALUES (132, 'Cañete', 15);
INSERT INTO provinces (id, name, department_id) VALUES (133, 'Huaral ', 15);
INSERT INTO provinces (id, name, department_id) VALUES (134, 'Huarochiri ', 15);
INSERT INTO provinces (id, name, department_id) VALUES (135, 'Huaura', 15);
INSERT INTO provinces (id, name, department_id) VALUES (136, 'Oyon', 15);
INSERT INTO provinces (id, name, department_id) VALUES (137, 'Yauyos ', 15);
INSERT INTO provinces (id, name, department_id) VALUES (138, 'Maynas', 16);
INSERT INTO provinces (id, name, department_id) VALUES (139, 'Alto Amazonas', 16);
INSERT INTO provinces (id, name, department_id) VALUES (140, 'Loreto', 16);
INSERT INTO provinces (id, name, department_id) VALUES (141, 'Mariscal Ramon Castilla', 16);
INSERT INTO provinces (id, name, department_id) VALUES (142, 'Requena ', 16);
INSERT INTO provinces (id, name, department_id) VALUES (143, 'Ucayali ', 16);
INSERT INTO provinces (id, name, department_id) VALUES (144, 'Tambopata ', 17);
INSERT INTO provinces (id, name, department_id) VALUES (145, 'Manu ', 17);
INSERT INTO provinces (id, name, department_id) VALUES (146, 'Tahuamanu', 17);
INSERT INTO provinces (id, name, department_id) VALUES (147, 'Mariscal Nieto', 18);
INSERT INTO provinces (id, name, department_id) VALUES (148, 'General Sanchez Cerro', 18);
INSERT INTO provinces (id, name, department_id) VALUES (149, 'Ilo', 18);
INSERT INTO provinces (id, name, department_id) VALUES (150, 'Pasco', 19);
INSERT INTO provinces (id, name, department_id) VALUES (151, 'Daniel Alcides Carrion', 19);
INSERT INTO provinces (id, name, department_id) VALUES (152, 'Oxapampa', 19);
INSERT INTO provinces (id, name, department_id) VALUES (153, 'Piura', 20);
INSERT INTO provinces (id, name, department_id) VALUES (154, 'Ayabaca', 20);
INSERT INTO provinces (id, name, department_id) VALUES (155, 'Huancabamba', 20);
INSERT INTO provinces (id, name, department_id) VALUES (156, 'Morropon', 20);
INSERT INTO provinces (id, name, department_id) VALUES (157, 'Paita', 20);
INSERT INTO provinces (id, name, department_id) VALUES (158, 'Sullana ', 20);
INSERT INTO provinces (id, name, department_id) VALUES (159, 'Talara ', 20);
INSERT INTO provinces (id, name, department_id) VALUES (160, 'Sechura ', 20);
INSERT INTO provinces (id, name, department_id) VALUES (161, 'Puno', 21);
INSERT INTO provinces (id, name, department_id) VALUES (162, 'Azangaro', 21);
INSERT INTO provinces (id, name, department_id) VALUES (163, 'Carabaya ', 21);
INSERT INTO provinces (id, name, department_id) VALUES (164, 'Chucuito ', 21);
INSERT INTO provinces (id, name, department_id) VALUES (165, 'El Collao  ', 21);
INSERT INTO provinces (id, name, department_id) VALUES (166, 'Huancane ', 21);
INSERT INTO provinces (id, name, department_id) VALUES (167, 'Lampa', 21);
INSERT INTO provinces (id, name, department_id) VALUES (168, 'Melgar ', 21);
INSERT INTO provinces (id, name, department_id) VALUES (169, 'Moho ', 21);
INSERT INTO provinces (id, name, department_id) VALUES (170, 'San Antonio De Putina ', 21);
INSERT INTO provinces (id, name, department_id) VALUES (171, 'San Roman ', 21);
INSERT INTO provinces (id, name, department_id) VALUES (172, 'Sandia ', 21);
INSERT INTO provinces (id, name, department_id) VALUES (173, 'Yunguyo ', 21);
INSERT INTO provinces (id, name, department_id) VALUES (174, 'Moyobamba ', 22);
INSERT INTO provinces (id, name, department_id) VALUES (175, 'Bellavista ', 22);
INSERT INTO provinces (id, name, department_id) VALUES (176, 'El Dorado ', 22);
INSERT INTO provinces (id, name, department_id) VALUES (177, 'Huallaga ', 22);
INSERT INTO provinces (id, name, department_id) VALUES (178, 'Lamas', 22);
INSERT INTO provinces (id, name, department_id) VALUES (179, 'Mariscal Caceres', 22);
INSERT INTO provinces (id, name, department_id) VALUES (180, 'Picota', 22);
INSERT INTO provinces (id, name, department_id) VALUES (181, 'Rioja', 22);
INSERT INTO provinces (id, name, department_id) VALUES (182, 'San Martin  ', 22);
INSERT INTO provinces (id, name, department_id) VALUES (183, 'Tocache ', 22);
INSERT INTO provinces (id, name, department_id) VALUES (184, 'Tacna', 23);
INSERT INTO provinces (id, name, department_id) VALUES (185, 'Candarave', 23);
INSERT INTO provinces (id, name, department_id) VALUES (186, 'Jorge Basadre', 23);
INSERT INTO provinces (id, name, department_id) VALUES (187, 'Tarata', 23);
INSERT INTO provinces (id, name, department_id) VALUES (188, 'Tumbes', 24);
INSERT INTO provinces (id, name, department_id) VALUES (189, 'Contralmirante Villar', 24);
INSERT INTO provinces (id, name, department_id) VALUES (190, 'Zarumilla', 24);
INSERT INTO provinces (id, name, department_id) VALUES (191, 'Coronel Portillo', 25);
INSERT INTO provinces (id, name, department_id) VALUES (192, 'Atalaya', 25);
INSERT INTO provinces (id, name, department_id) VALUES (193, 'Padre Abad', 25);
INSERT INTO provinces (id, name, department_id) VALUES (194, 'Purus', 25);

-- migrate:down

DELETE FROM provinces;