-- migrate:up

INSERT INTO sections 
(id, name, description, image_url, course_id)
VALUES
(1, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 1),
(2, 'Explorando y Aprendiendo', 'Actividades lúdicas para descubrimiento guiado', 'section.png', 1),
(3, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 2),
(4, 'Explorando y Aprendiendo', 'Actividades lúdicas para descubrimiento guiado', 'section.png', 2),
(5, 'Jugando Crecemos', 'Aprendizaje a través del juego y la diversión', 'section.png', 3),
(6, 'Explorando y Aprendiendo', 'Actividades lúdicas para descubrimiento guiado', 'section.png', 3),
(7, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 4),
(8, 'Jugando Crecemos', 'Aprendizaje a través del juego y la diversión', 'section.png', 4),
(9, 'Jugando Crecemos', 'Aprendizaje a través del juego y la diversión', 'section.png', 5),
(10, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 5),
(11, 'Explorando y Aprendiendo', 'Actividades lúdicas para descubrimiento guiado', 'section.png', 6),
(12, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 6),
(13, 'Jugando Crecemos', 'Aprendizaje a través del juego y la diversión', 'section.png', 7),
(14, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 7),
(15, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 8),
(16, 'Jugando Crecemos', 'Aprendizaje a través del juego y la diversión', 'section.png', 8),
(17, 'Jugando Crecemos', 'Aprendizaje a través del juego y la diversión', 'section.png', 9),
(18, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 9),
(19, 'Explorando y Aprendiendo', 'Actividades lúdicas para descubrimiento guiado', 'section.png', 9),
(20, 'Jugando Crecemos', 'Aprendizaje a través del juego y la diversión', 'section.png', 10),
(21, 'Explorando y Aprendiendo', 'Actividades lúdicas para descubrimiento guiado', 'section.png', 10),
(22, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 10),
(23, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 11),
(24, 'Explorando y Aprendiendo', 'Actividades lúdicas para descubrimiento guiado', 'section.png', 11),
(25, 'Jugando Crecemos', 'Aprendizaje a través del juego y la diversión', 'section.png', 11),
(26, 'Explorando y Aprendiendo', 'Actividades lúdicas para descubrimiento guiado', 'section.png', 12),
(27, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 12),
(28, 'Jugando Crecemos', 'Aprendizaje a través del juego y la diversión', 'section.png', 12),
(29, 'Expresión Oral', 'Técnicas para mejorar la comunicación verbal', 'section.png', 13),
(30, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 13),
(31, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 14),
(32, 'Razonamiento Matemático', 'Desarrollo del pensamiento lógico matemático', 'section.png', 14),
(33, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 15),
(34, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 15),
(35, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 16),
(36, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 16),
(37, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 17),
(38, 'Apreciación Artística', 'Análisis y valoración de obras de arte', 'section.png', 17),
(39, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 18),
(40, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 18),
(41, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 19),
(42, 'Vocabulary', 'Ampliación de vocabulario en inglés', 'section.png', 19),
(43, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 20),
(44, 'Expresión Oral', 'Técnicas para mejorar la comunicación verbal', 'section.png', 20),
(45, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 21),
(46, 'Operaciones Básicas', 'Práctica de operaciones fundamentales', 'section.png', 21),
(47, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 22),
(48, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 22),
(49, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 23),
(50, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 23),
(51, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 24),
(52, 'Apreciación Artística', 'Análisis y valoración de obras de arte', 'section.png', 24),
(53, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 25),
(54, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 25),
(55, 'Vocabulary', 'Ampliación de vocabulario en inglés', 'section.png', 26),
(56, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 26),
(57, 'Expresión Oral', 'Técnicas para mejorar la comunicación verbal', 'section.png', 27),
(58, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 27),
(59, 'Operaciones Básicas', 'Práctica de operaciones fundamentales', 'section.png', 28),
(60, 'Razonamiento Matemático', 'Desarrollo del pensamiento lógico matemático', 'section.png', 28),
(61, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 29),
(62, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 29),
(63, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 30),
(64, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 30),
(65, 'Apreciación Artística', 'Análisis y valoración de obras de arte', 'section.png', 31),
(66, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 31),
(67, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 32),
(68, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 32),
(69, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 33),
(70, 'Vocabulary', 'Ampliación de vocabulario en inglés', 'section.png', 33),
(71, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 34),
(72, 'Comprensión Lectora', 'Desarrollo de habilidades de comprensión de textos', 'section.png', 34),
(73, 'Operaciones Básicas', 'Práctica de operaciones fundamentales', 'section.png', 35),
(74, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 35),
(75, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 36),
(76, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 36),
(77, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 37),
(78, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 37),
(79, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 38),
(80, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 38),
(81, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 39),
(82, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 39),
(83, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 40),
(84, 'Grammar', 'Estructuras gramaticales del inglés', 'section.png', 40),
(85, 'Expresión Oral', 'Técnicas para mejorar la comunicación verbal', 'section.png', 41),
(86, 'Comprensión Lectora', 'Desarrollo de habilidades de comprensión de textos', 'section.png', 41),
(87, 'Razonamiento Matemático', 'Desarrollo del pensamiento lógico matemático', 'section.png', 42),
(88, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 42),
(89, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 43),
(90, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 43),
(91, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 44),
(92, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 44),
(93, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 45),
(94, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 45),
(95, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 46),
(96, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 46),
(97, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 47),
(98, 'Vocabulary', 'Ampliación de vocabulario en inglés', 'section.png', 47),
(99, 'Comprensión Lectora', 'Desarrollo de habilidades de comprensión de textos', 'section.png', 48),
(100, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 48),
(101, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 49),
(102, 'Operaciones Básicas', 'Práctica de operaciones fundamentales', 'section.png', 49),
(103, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 50),
(104, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 50),
(105, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 51),
(106, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 51),
(107, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 52),
(108, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 52),
(109, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 53),
(110, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 53),
(111, 'Grammar', 'Estructuras gramaticales del inglés', 'section.png', 54),
(112, 'Vocabulary', 'Ampliación de vocabulario en inglés', 'section.png', 54),
(113, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 55),
(114, 'Expresión Oral', 'Técnicas para mejorar la comunicación verbal', 'section.png', 55),
(115, 'Operaciones Básicas', 'Práctica de operaciones fundamentales', 'section.png', 56),
(116, 'Razonamiento Matemático', 'Desarrollo del pensamiento lógico matemático', 'section.png', 56),
(117, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 57),
(118, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 57),
(119, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 57),
(120, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 58),
(121, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 58),
(122, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 59),
(123, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 59),
(124, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 60),
(125, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 60),
(126, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 60),
(127, 'Vocabulary', 'Ampliación de vocabulario en inglés', 'section.png', 61),
(128, 'Grammar', 'Estructuras gramaticales del inglés', 'section.png', 61),
(129, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 61),
(130, 'Apreciación Artística', 'Análisis y valoración de obras de arte', 'section.png', 62),
(131, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 62),
(132, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 63),
(133, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 63),
(134, 'Orientación Personal', 'Apoyo en el desarrollo personal', 'section.png', 64),
(135, 'Reflexión y Valores', 'Desarrollo espiritual y ético', 'section.png', 64),
(136, 'Proyecto de Vida', 'Planificación de metas personales', 'section.png', 65),
(137, 'Orientación Personal', 'Apoyo en el desarrollo personal', 'section.png', 65),
(138, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 66),
(139, 'Expresión Oral', 'Técnicas para mejorar la comunicación verbal', 'section.png', 66),
(140, 'Operaciones Básicas', 'Práctica de operaciones fundamentales', 'section.png', 67),
(141, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 67),
(142, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 68),
(143, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 68),
(144, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 69),
(145, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 69),
(146, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 70),
(147, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 70),
(148, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 71),
(149, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 71),
(150, 'Grammar', 'Estructuras gramaticales del inglés', 'section.png', 72),
(151, 'Vocabulary', 'Ampliación de vocabulario en inglés', 'section.png', 72),
(152, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 72),
(153, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 73),
(154, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 73),
(155, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 74),
(156, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 74),
(157, 'Reflexión y Valores', 'Desarrollo espiritual y ético', 'section.png', 75),
(158, 'Orientación Personal', 'Apoyo en el desarrollo personal', 'section.png', 75),
(159, 'Proyecto de Vida', 'Planificación de metas personales', 'section.png', 76),
(160, 'Reflexión y Valores', 'Desarrollo espiritual y ético', 'section.png', 76),
(161, 'Expresión Oral', 'Técnicas para mejorar la comunicación verbal', 'section.png', 77),
(162, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 77),
(163, 'Operaciones Básicas', 'Práctica de operaciones fundamentales', 'section.png', 78),
(164, 'Razonamiento Matemático', 'Desarrollo del pensamiento lógico matemático', 'section.png', 78),
(165, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 78),
(166, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 79),
(167, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 79),
(168, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 80),
(169, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 80),
(170, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 81),
(171, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 81),
(172, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 82),
(173, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 82),
(174, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 82),
(175, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 83),
(176, 'Grammar', 'Estructuras gramaticales del inglés', 'section.png', 83),
(177, 'Vocabulary', 'Ampliación de vocabulario en inglés', 'section.png', 83),
(178, 'Apreciación Artística', 'Análisis y valoración de obras de arte', 'section.png', 84),
(179, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 84),
(180, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 84),
(181, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 85),
(182, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 85),
(183, 'Reflexión y Valores', 'Desarrollo espiritual y ético', 'section.png', 86),
(184, 'Proyecto de Vida', 'Planificación de metas personales', 'section.png', 86),
(185, 'Orientación Personal', 'Apoyo en el desarrollo personal', 'section.png', 86),
(186, 'Proyecto de Vida', 'Planificación de metas personales', 'section.png', 87),
(187, 'Orientación Personal', 'Apoyo en el desarrollo personal', 'section.png', 87),
(188, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 88),
(189, 'Expresión Oral', 'Técnicas para mejorar la comunicación verbal', 'section.png', 88),
(190, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 89),
(191, 'Razonamiento Matemático', 'Desarrollo del pensamiento lógico matemático', 'section.png', 89),
(192, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 90),
(193, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 90),
(194, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 91),
(195, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 91),
(196, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 91),
(197, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 92),
(198, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 92),
(199, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 93),
(200, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 93),
(201, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 93),
(202, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 94),
(203, 'Vocabulary', 'Ampliación de vocabulario en inglés', 'section.png', 94),
(204, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 95),
(205, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 95),
(206, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 96),
(207, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 96),
(208, 'Orientación Personal', 'Apoyo en el desarrollo personal', 'section.png', 97),
(209, 'Reflexión y Valores', 'Desarrollo espiritual y ético', 'section.png', 97),
(210, 'Proyecto de Vida', 'Planificación de metas personales', 'section.png', 97),
(211, 'Proyecto de Vida', 'Planificación de metas personales', 'section.png', 98),
(212, 'Reflexión y Valores', 'Desarrollo espiritual y ético', 'section.png', 98),
(213, 'Comprensión Lectora', 'Desarrollo de habilidades de comprensión de textos', 'section.png', 99),
(214, 'Expresión Oral', 'Técnicas para mejorar la comunicación verbal', 'section.png', 99),
(215, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 99),
(216, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 100),
(217, 'Operaciones Básicas', 'Práctica de operaciones fundamentales', 'section.png', 100),
(218, 'Razonamiento Matemático', 'Desarrollo del pensamiento lógico matemático', 'section.png', 100),
(219, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 101),
(220, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 101),
(221, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 102),
(222, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 102),
(223, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 103),
(224, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 103),
(225, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 103),
(226, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 104),
(227, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 104),
(228, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 104),
(229, 'Grammar', 'Estructuras gramaticales del inglés', 'section.png', 105),
(230, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 105),
(231, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 106),
(232, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 106),
(233, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 107),
(234, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 107),
(235, 'Orientación Personal', 'Apoyo en el desarrollo personal', 'section.png', 108),
(236, 'Proyecto de Vida', 'Planificación de metas personales', 'section.png', 108),
(237, 'Proyecto de Vida', 'Planificación de metas personales', 'section.png', 109),
(238, 'Reflexión y Valores', 'Desarrollo espiritual y ético', 'section.png', 109),
(239, 'Apreciación Artística', 'Análisis y valoración de obras de arte', 'section.png', 110),
(240, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 110),
(241, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 110),
(242, 'Apreciación Artística', 'Análisis y valoración de obras de arte', 'section.png', 111),
(243, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 111),
(244, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 111),
(245, 'Apreciación Artística', 'Análisis y valoración de obras de arte', 'section.png', 112),
(246, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 112),
(247, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 112),
(248, 'Salud y Bienestar', 'Hábitos saludables y cuidado del cuerpo', 'section.png', 113),
(249, 'Coordinación Motriz', 'Ejercicios para mejorar la coordinación', 'section.png', 113),
(250, 'Deportes y Juegos', 'Práctica de diferentes disciplinas deportivas', 'section.png', 113),
(251, 'Coordinación Motriz', 'Ejercicios para mejorar la coordinación', 'section.png', 114),
(252, 'Deportes y Juegos', 'Práctica de diferentes disciplinas deportivas', 'section.png', 114),
(253, 'Salud y Bienestar', 'Hábitos saludables y cuidado del cuerpo', 'section.png', 114),
(254, 'Salud y Bienestar', 'Hábitos saludables y cuidado del cuerpo', 'section.png', 115),
(255, 'Coordinación Motriz', 'Ejercicios para mejorar la coordinación', 'section.png', 115),
(256, 'Deportes y Juegos', 'Práctica de diferentes disciplinas deportivas', 'section.png', 115),
(257, 'Operaciones Básicas', 'Práctica de operaciones fundamentales', 'section.png', 116),
(258, 'Razonamiento Matemático', 'Desarrollo del pensamiento lógico matemático', 'section.png', 116),
(259, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 116),
(260, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 117),
(261, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 117),
(262, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 117),
(263, 'Nivel Intermedio', 'Profundización de técnicas y habilidades', 'section.png', 118),
(264, 'Nivel Avanzado', 'Perfeccionamiento y proyectos especiales', 'section.png', 118),
(265, 'Nivel Básico', 'Introducción y fundamentos del taller', 'section.png', 118);


-- migrate:down

DELETE FROM sections WHERE id <= 265;
ALTER TABLE sections AUTO_INCREMENT = 1;
