-- migrate:up

RENAME TABLE documents TO files;
ALTER TABLE files
CHANGE COLUMN title name VARCHAR(100) NOT NULL,
CHANGE COLUMN autogenerated_title autogenerated_name TEXT,
MODIFY COLUMN uploaded_by INT UNSIGNED NULL;
ALTER TABLE files
ADD COLUMN visible BOOLEAN NULL;


-- migrate:down

ALTER TABLE files
DROP COLUMN visible;
ALTER TABLE files
CHANGE COLUMN name title VARCHAR(100) NOT NULL,
CHANGE COLUMN autogenerated_name autogenerated_title TEXT,
MODIFY COLUMN uploaded_by INT UNSIGNED NOT NULL;
RENAME TABLE files TO documents;