-- migrate:up

INSERT INTO sections 
(id, name, description, image_url, code, course_id)
VALUES
(1, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 'S-1', 1),
(2, 'Explorando y Aprendiendo', 'Actividades lúdicas para descubrimiento guiado', 'section.png', 'S-2', 1),
(3, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 'S-3', 2),
(4, 'Explorando y Aprendiendo', 'Actividades lúdicas para descubrimiento guiado', 'section.png', 'S-4', 2),
(5, 'Jugando Crecemos', 'Aprendizaje a través del juego y la diversión', 'section.png', 'S-5', 3),
(6, 'Explorando y Aprendiendo', 'Actividades lúdicas para descubrimiento guiado', 'section.png', 'S-6', 3),
(7, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 'S-7', 4),
(8, 'Jugando Crecemos', 'Aprendizaje a través del juego y la diversión', 'section.png', 'S-8', 4),
(9, 'Jugando Crecemos', 'Aprendizaje a través del juego y la diversión', 'section.png', 'S-9', 5),
(10, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 'S-10', 5),
(11, 'Explorando y Aprendiendo', 'Actividades lúdicas para descubrimiento guiado', 'section.png', 'S-11', 6),
(12, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 'S-12', 6),
(13, 'Jugando Crecemos', 'Aprendizaje a través del juego y la diversión', 'section.png', 'S-13', 7),
(14, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 'S-14', 7),
(15, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 'S-15', 8),
(16, 'Jugando Crecemos', 'Aprendizaje a través del juego y la diversión', 'section.png', 'S-16', 8),
(17, 'Jugando Crecemos', 'Aprendizaje a través del juego y la diversión', 'section.png', 'S-17', 9),
(18, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 'S-18', 9),
(19, 'Explorando y Aprendiendo', 'Actividades lúdicas para descubrimiento guiado', 'section.png', 'S-19', 9),
(20, 'Jugando Crecemos', 'Aprendizaje a través del juego y la diversión', 'section.png', 'S-20', 10),
(21, 'Explorando y Aprendiendo', 'Actividades lúdicas para descubrimiento guiado', 'section.png', 'S-21', 10),
(22, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 'S-22', 10),
(23, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 'S-23', 11),
(24, 'Explorando y Aprendiendo', 'Actividades lúdicas para descubrimiento guiado', 'section.png', 'S-24', 11),
(25, 'Jugando Crecemos', 'Aprendizaje a través del juego y la diversión', 'section.png', 'S-25', 11),
(26, 'Explorando y Aprendiendo', 'Actividades lúdicas para descubrimiento guiado', 'section.png', 'S-26', 12),
(27, 'Descubriendo el Mundo', 'Exploración del entorno cercano', 'section.png', 'S-27', 12),
(28, 'Jugando Crecemos', 'Aprendizaje a través del juego y la diversión', 'section.png', 'S-28', 12),
(29, 'Expresión Oral', 'Técnicas para mejorar la comunicación verbal', 'section.png', 'S-29', 13),
(30, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 'S-30', 13),
(31, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 'S-31', 14),
(32, 'Razonamiento Matemático', 'Desarrollo del pensamiento lógico matemático', 'section.png', 'S-32', 14),
(33, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 'S-33', 15),
(34, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-34', 15),
(35, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 'S-35', 16),
(36, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 'S-36', 16),
(37, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 'S-37', 17),
(38, 'Apreciación Artística', 'Análisis y valoración de obras de arte', 'section.png', 'S-38', 17),
(39, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 'S-39', 18),
(40, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-40', 18),
(41, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 'S-41', 19),
(42, 'Vocabulary', 'Ampliación de vocabulario en inglés', 'section.png', 'S-42', 19),
(43, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 'S-43', 20),
(44, 'Expresión Oral', 'Técnicas para mejorar la comunicación verbal', 'section.png', 'S-44', 20),
(45, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 'S-45', 21),
(46, 'Operaciones Básicas', 'Práctica de operaciones fundamentales', 'section.png', 'S-46', 21),
(47, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 'S-47', 22),
(48, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 'S-48', 22),
(49, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 'S-49', 23),
(50, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 'S-50', 23),
(51, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 'S-51', 24),
(52, 'Apreciación Artística', 'Análisis y valoración de obras de arte', 'section.png', 'S-52', 24),
(53, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 'S-53', 25),
(54, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 'S-54', 25),
(55, 'Vocabulary', 'Ampliación de vocabulario en inglés', 'section.png', 'S-55', 26),
(56, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 'S-56', 26),
(57, 'Expresión Oral', 'Técnicas para mejorar la comunicación verbal', 'section.png', 'S-57', 27),
(58, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 'S-58', 27),
(59, 'Operaciones Básicas', 'Práctica de operaciones fundamentales', 'section.png', 'S-59', 28),
(60, 'Razonamiento Matemático', 'Desarrollo del pensamiento lógico matemático', 'section.png', 'S-60', 28),
(61, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 'S-61', 29),
(62, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-62', 29),
(63, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 'S-63', 30),
(64, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 'S-64', 30),
(65, 'Apreciación Artística', 'Análisis y valoración de obras de arte', 'section.png', 'S-65', 31),
(66, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 'S-66', 31),
(67, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-67', 32),
(68, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 'S-68', 32),
(69, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 'S-69', 33),
(70, 'Vocabulary', 'Ampliación de vocabulario en inglés', 'section.png', 'S-70', 33),
(71, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 'S-71', 34),
(72, 'Comprensión Lectora', 'Desarrollo de habilidades de comprensión de textos', 'section.png', 'S-72', 34),
(73, 'Operaciones Básicas', 'Práctica de operaciones fundamentales', 'section.png', 'S-73', 35),
(74, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 'S-74', 35),
(75, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 'S-75', 36),
(76, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-76', 36),
(77, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 'S-77', 37),
(78, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 'S-78', 37),
(79, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 'S-79', 38),
(80, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 'S-80', 38),
(81, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-81', 39),
(82, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 'S-82', 39),
(83, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 'S-83', 40),
(84, 'Grammar', 'Estructuras gramaticales del inglés', 'section.png', 'S-84', 40),
(85, 'Expresión Oral', 'Técnicas para mejorar la comunicación verbal', 'section.png', 'S-85', 41),
(86, 'Comprensión Lectora', 'Desarrollo de habilidades de comprensión de textos', 'section.png', 'S-86', 41),
(87, 'Razonamiento Matemático', 'Desarrollo del pensamiento lógico matemático', 'section.png', 'S-87', 42),
(88, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 'S-88', 42),
(89, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 'S-89', 43),
(90, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-90', 43),
(91, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 'S-91', 44),
(92, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 'S-92', 44),
(93, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 'S-93', 45),
(94, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 'S-94', 45),
(95, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-95', 46),
(96, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 'S-96', 46),
(97, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 'S-97', 47),
(98, 'Vocabulary', 'Ampliación de vocabulario en inglés', 'section.png', 'S-98', 47),
(99, 'Comprensión Lectora', 'Desarrollo de habilidades de comprensión de textos', 'section.png', 'S-99', 48),
(100, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 'S-100', 48),
(101, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 'S-101', 49),
(102, 'Operaciones Básicas', 'Práctica de operaciones fundamentales', 'section.png', 'S-102', 49),
(103, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-103', 50),
(104, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 'S-104', 50),
(105, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 'S-105', 51),
(106, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 'S-106', 51),
(107, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 'S-107', 52),
(108, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 'S-108', 52),
(109, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 'S-109', 53),
(110, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 'S-110', 53),
(111, 'Grammar', 'Estructuras gramaticales del inglés', 'section.png', 'S-111', 54),
(112, 'Vocabulary', 'Ampliación de vocabulario en inglés', 'section.png', 'S-112', 54),
(113, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 'S-113', 55),
(114, 'Expresión Oral', 'Técnicas para mejorar la comunicación verbal', 'section.png', 'S-114', 55),
(115, 'Operaciones Básicas', 'Práctica de operaciones fundamentales', 'section.png', 'S-115', 56),
(116, 'Razonamiento Matemático', 'Desarrollo del pensamiento lógico matemático', 'section.png', 'S-116', 56),
(117, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-117', 57),
(118, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 'S-118', 57),
(119, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 'S-119', 57),
(120, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 'S-120', 58),
(121, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 'S-121', 58),
(122, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 'S-122', 59),
(123, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 'S-123', 59),
(124, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 'S-124', 60),
(125, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 'S-125', 60),
(126, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 'S-126', 60),
(127, 'Vocabulary', 'Ampliación de vocabulario en inglés', 'section.png', 'S-127', 61),
(128, 'Grammar', 'Estructuras gramaticales del inglés', 'section.png', 'S-128', 61),
(129, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 'S-129', 61),
(130, 'Apreciación Artística', 'Análisis y valoración de obras de arte', 'section.png', 'S-130', 62),
(131, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 'S-131', 62),
(132, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-132', 63),
(133, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 'S-133', 63),
(134, 'Orientación Personal', 'Apoyo en el desarrollo personal', 'section.png', 'S-134', 64),
(135, 'Reflexión y Valores', 'Desarrollo espiritual y ético', 'section.png', 'S-135', 64),
(136, 'Proyecto de Vida', 'Planificación de metas personales', 'section.png', 'S-136', 65),
(137, 'Orientación Personal', 'Apoyo en el desarrollo personal', 'section.png', 'S-137', 65),
(138, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 'S-138', 66),
(139, 'Expresión Oral', 'Técnicas para mejorar la comunicación verbal', 'section.png', 'S-139', 66),
(140, 'Operaciones Básicas', 'Práctica de operaciones fundamentales', 'section.png', 'S-140', 67),
(141, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 'S-141', 67),
(142, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-142', 68),
(143, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 'S-143', 68),
(144, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 'S-144', 69),
(145, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 'S-145', 69),
(146, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 'S-146', 70),
(147, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 'S-147', 70),
(148, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 'S-148', 71),
(149, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 'S-149', 71),
(150, 'Grammar', 'Estructuras gramaticales del inglés', 'section.png', 'S-150', 72),
(151, 'Vocabulary', 'Ampliación de vocabulario en inglés', 'section.png', 'S-151', 72),
(152, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 'S-152', 72),
(153, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 'S-153', 73),
(154, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 'S-154', 73),
(155, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 'S-155', 74),
(156, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-156', 74),
(157, 'Reflexión y Valores', 'Desarrollo espiritual y ético', 'section.png', 'S-157', 75),
(158, 'Orientación Personal', 'Apoyo en el desarrollo personal', 'section.png', 'S-158', 75),
(159, 'Proyecto de Vida', 'Planificación de metas personales', 'section.png', 'S-159', 76),
(160, 'Reflexión y Valores', 'Desarrollo espiritual y ético', 'section.png', 'S-160', 76),
(161, 'Expresión Oral', 'Técnicas para mejorar la comunicación verbal', 'section.png', 'S-161', 77),
(162, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 'S-162', 77),
(163, 'Operaciones Básicas', 'Práctica de operaciones fundamentales', 'section.png', 'S-163', 78),
(164, 'Razonamiento Matemático', 'Desarrollo del pensamiento lógico matemático', 'section.png', 'S-164', 78),
(165, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 'S-165', 78),
(166, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 'S-166', 79),
(167, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-167', 79),
(168, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 'S-168', 80),
(169, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 'S-169', 80),
(170, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 'S-170', 81),
(171, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 'S-171', 81),
(172, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 'S-172', 82),
(173, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 'S-173', 82),
(174, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 'S-174', 82),
(175, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 'S-175', 83),
(176, 'Grammar', 'Estructuras gramaticales del inglés', 'section.png', 'S-176', 83),
(177, 'Vocabulary', 'Ampliación de vocabulario en inglés', 'section.png', 'S-177', 83),
(178, 'Apreciación Artística', 'Análisis y valoración de obras de arte', 'section.png', 'S-178', 84),
(179, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 'S-179', 84),
(180, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 'S-180', 84),
(181, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-181', 85),
(182, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 'S-182', 85),
(183, 'Reflexión y Valores', 'Desarrollo espiritual y ético', 'section.png', 'S-183', 86),
(184, 'Proyecto de Vida', 'Planificación de metas personales', 'section.png', 'S-184', 86),
(185, 'Orientación Personal', 'Apoyo en el desarrollo personal', 'section.png', 'S-185', 86),
(186, 'Proyecto de Vida', 'Planificación de metas personales', 'section.png', 'S-186', 87),
(187, 'Orientación Personal', 'Apoyo en el desarrollo personal', 'section.png', 'S-187', 87),
(188, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 'S-188', 88),
(189, 'Expresión Oral', 'Técnicas para mejorar la comunicación verbal', 'section.png', 'S-189', 88),
(190, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 'S-190', 89),
(191, 'Razonamiento Matemático', 'Desarrollo del pensamiento lógico matemático', 'section.png', 'S-191', 89),
(192, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-192', 90),
(193, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 'S-193', 90),
(194, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 'S-194', 91),
(195, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 'S-195', 91),
(196, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 'S-196', 91),
(197, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 'S-197', 92),
(198, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 'S-198', 92),
(199, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 'S-199', 93),
(200, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 'S-200', 93),
(201, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 'S-201', 93),
(202, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 'S-202', 94),
(203, 'Vocabulary', 'Ampliación de vocabulario en inglés', 'section.png', 'S-203', 94),
(204, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 'S-204', 95),
(205, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 'S-205', 95),
(206, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-206', 96),
(207, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 'S-207', 96),
(208, 'Orientación Personal', 'Apoyo en el desarrollo personal', 'section.png', 'S-208', 97),
(209, 'Reflexión y Valores', 'Desarrollo espiritual y ético', 'section.png', 'S-209', 97),
(210, 'Proyecto de Vida', 'Planificación de metas personales', 'section.png', 'S-210', 97),
(211, 'Proyecto de Vida', 'Planificación de metas personales', 'section.png', 'S-211', 98),
(212, 'Reflexión y Valores', 'Desarrollo espiritual y ético', 'section.png', 'S-212', 98),
(213, 'Comprensión Lectora', 'Desarrollo de habilidades de comprensión de textos', 'section.png', 'S-213', 99),
(214, 'Expresión Oral', 'Técnicas para mejorar la comunicación verbal', 'section.png', 'S-214', 99),
(215, 'Producción de Textos', 'Creación y redacción de diferentes tipos de textos', 'section.png', 'S-215', 99),
(216, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 'S-216', 100),
(217, 'Operaciones Básicas', 'Práctica de operaciones fundamentales', 'section.png', 'S-217', 100),
(218, 'Razonamiento Matemático', 'Desarrollo del pensamiento lógico matemático', 'section.png', 'S-218', 100),
(219, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 'S-219', 101),
(220, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-220', 101),
(221, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 'S-221', 102),
(222, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 'S-222', 102),
(223, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 'S-223', 103),
(224, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 'S-224', 103),
(225, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 'S-225', 103),
(226, 'Análisis Histórico', 'Interpretación de eventos históricos', 'section.png', 'S-226', 104),
(227, 'Geografía y Espacio', 'Estudio del territorio y sus características', 'section.png', 'S-227', 104),
(228, 'Formación Ciudadana', 'Desarrollo de valores cívicos y ciudadanos', 'section.png', 'S-228', 104),
(229, 'Grammar', 'Estructuras gramaticales del inglés', 'section.png', 'S-229', 105),
(230, 'Conversation', 'Práctica de conversación en inglés', 'section.png', 'S-230', 105),
(231, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 'S-231', 106),
(232, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 'S-232', 106),
(233, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 'S-233', 107),
(234, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 'S-234', 107),
(235, 'Orientación Personal', 'Apoyo en el desarrollo personal', 'section.png', 'S-235', 108),
(236, 'Proyecto de Vida', 'Planificación de metas personales', 'section.png', 'S-236', 108),
(237, 'Proyecto de Vida', 'Planificación de metas personales', 'section.png', 'S-237', 109),
(238, 'Reflexión y Valores', 'Desarrollo espiritual y ético', 'section.png', 'S-238', 109),
(239, 'Apreciación Artística', 'Análisis y valoración de obras de arte', 'section.png', 'S-239', 110),
(240, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 'S-240', 110),
(241, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 'S-241', 110),
(242, 'Apreciación Artística', 'Análisis y valoración de obras de arte', 'section.png', 'S-242', 111),
(243, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 'S-243', 111),
(244, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 'S-244', 111),
(245, 'Apreciación Artística', 'Análisis y valoración de obras de arte', 'section.png', 'S-245', 112),
(246, 'Creación y Expresión', 'Desarrollo de la creatividad artística', 'section.png', 'S-246', 112),
(247, 'Técnicas Artísticas', 'Práctica de diferentes técnicas de arte', 'section.png', 'S-247', 112),
(248, 'Salud y Bienestar', 'Hábitos saludables y cuidado del cuerpo', 'section.png', 'S-248', 113),
(249, 'Coordinación Motriz', 'Ejercicios para mejorar la coordinación', 'section.png', 'S-249', 113),
(250, 'Deportes y Juegos', 'Práctica de diferentes disciplinas deportivas', 'section.png', 'S-250', 113),
(251, 'Coordinación Motriz', 'Ejercicios para mejorar la coordinación', 'section.png', 'S-251', 114),
(252, 'Deportes y Juegos', 'Práctica de diferentes disciplinas deportivas', 'section.png', 'S-252', 114),
(253, 'Salud y Bienestar', 'Hábitos saludables y cuidado del cuerpo', 'section.png', 'S-253', 114),
(254, 'Salud y Bienestar', 'Hábitos saludables y cuidado del cuerpo', 'section.png', 'S-254', 115),
(255, 'Coordinación Motriz', 'Ejercicios para mejorar la coordinación', 'section.png', 'S-255', 115),
(256, 'Deportes y Juegos', 'Práctica de diferentes disciplinas deportivas', 'section.png', 'S-256', 115),
(257, 'Operaciones Básicas', 'Práctica de operaciones fundamentales', 'section.png', 'S-257', 116),
(258, 'Razonamiento Matemático', 'Desarrollo del pensamiento lógico matemático', 'section.png', 'S-258', 116),
(259, 'Resolución de Problemas', 'Estrategias para resolver problemas matemáticos', 'section.png', 'S-259', 116),
(260, 'Investigación Científica', 'Métodos y técnicas de investigación', 'section.png', 'S-260', 117),
(261, 'Experimentación', 'Prácticas de laboratorio y experimentos', 'section.png', 'S-261', 117),
(262, 'Naturaleza y Ambiente', 'Estudio del entorno natural', 'section.png', 'S-262', 117),
(263, 'Nivel Intermedio', 'Profundización de técnicas y habilidades', 'section.png', 'S-263', 118),
(264, 'Nivel Avanzado', 'Perfeccionamiento y proyectos especiales', 'section.png', 'S-264', 118),
(265, 'Nivel Básico', 'Introducción y fundamentos del taller', 'section.png', 'S-265', 118);


-- migrate:down

DELETE FROM sections WHERE id <= 265;
ALTER TABLE sections AUTO_INCREMENT = 1;
