// models/document.js
import { DataTypes } from 'sequelize';
import sequelize from '../../configs/database.js';

const Document = sequelize.define('Document', {
  id: {
    type: DataTypes.INTEGER.UNSIGNED,
    autoIncrement: true,
    primaryKey: true,
    allowNull: false
  },
  folder_id: {
    type: DataTypes.INTEGER.UNSIGNED,
    allowNull: false,
    references: {
      model: 'folders',
      key: 'id'
    }
  },
  title: {
    type: DataTypes.STRING(100),
    allowNull: false
  },
  autogenerated_title: {
    type: DataTypes.TEXT,
    allowNull: true
  },
  url: {
    type: DataTypes.STRING(255),
    allowNull: false
  },
  uploaded_by: {
    type: DataTypes.INTEGER.UNSIGNED,
    allowNull: false,
    references: {
      model: 'workers',
      key: 'id'
    }
  },
  created: {
    type: DataTypes.DATE,
    allowNull: false,
    defaultValue: DataTypes.NOW
  },
  updated: {
    type: DataTypes.DATE,
    allowNull: false,
    defaultValue: DataTypes.NOW
  }
}, {
  tableName: 'documents',
  timestamps: false, // Porque usamos campos created/updated personalizados
  indexes: [
    {
      name: 'idx_documents_folder_id',
      fields: ['folder_id']
    },
    {
      name: 'idx_documents_uploaded_by',
      fields: ['uploaded_by']
    }
  ]
});

export default Document;