import { DataTypes } from 'sequelize';
import sequelize from '../../configs/database.js';

const File = sequelize.define('File', {
  id: {
    type: DataTypes.INTEGER.UNSIGNED,
    autoIncrement: true,
    primaryKey: true,
    allowNull: false
  },
  folder_id: {
    type: DataTypes.INTEGER.UNSIGNED,
    allowNull: false,
    references: {
      model: 'folders',
      key: 'id'
    }
  },
  name: {
    type: DataTypes.STRING(100),
    allowNull: false
  },
  autogenerated_name: {
    type: DataTypes.TEXT,
    allowNull: true
  },
  url: {
    type: DataTypes.STRING(255),
    allowNull: false
  },
  uploaded_by: {
    type: DataTypes.INTEGER.UNSIGNED,
    allowNull: true,
    references: {
      model: 'workers',
      key: 'id'
    }
  },
  visible: {
    type: DataTypes.BOOLEAN,
    allowNull: true
  },
  created: {
    type: DataTypes.DATE,
    allowNull: false,
    defaultValue: DataTypes.NOW
  },
  updated: {
    type: DataTypes.DATE,
    allowNull: false,
    defaultValue: DataTypes.NOW
  }
}, {
  tableName: 'files',
  timestamps: false, // seguimos usando created/updated manuales
  indexes: [
    {
      name: 'idx_documents_folder_id', // puedes renombrarlo si quieres prolijidad
      fields: ['folder_id']
    },
    {
      name: 'idx_documents_uploaded_by',
      fields: ['uploaded_by']
    }
  ]
});

export default File;