// management/services/file_service.js
import sequelize from '../../configs/database.js';
import File from '../models/file.js';
import Folder from '../models/folder.js';

export const deleteFile = async (fileId) => {
  const transaction = await sequelize.transaction();

  try {
    const file = await File.findByPk(fileId);

    if (!file) {
      throw {
        status: 404,
        message: 'Archivo no encontrado',
        error: `File ID ${fileId}`
      };
    }

    // Eliminar registro (el archivo físico lo gestiona el servicio de storage)
    await file.destroy({ transaction });

    await transaction.commit();

  } catch (error) {
    await transaction.rollback();
    throw {
      status: error.status || 500,
      message: error.message || 'Error al eliminar el archivo',
      error: error.error || error.message
    };
  }
};

export const registerFile = async ({ folder_id, name, url, uploaded_by, autogenerated_name = null, visible = true }) => {
  const transaction = await sequelize.transaction();

  try {
    // Validar carpeta si viene
    if (folder_id) {
      const folder = await Folder.findByPk(folder_id);
      if (!folder) {
        throw {
          status: 404,
          message: 'Carpeta no encontrada',
          error: `Folder ID ${folder_id}`
        };
      }
    }

    const file = await File.create({
      folder_id,
      name,
      autogenerated_name,
      url,
      uploaded_by,
      visible,
      created: new Date(),
      updated: new Date()
    }, { transaction });

    await transaction.commit();

    return {
      id: file.id,
      name: file.name,
      url: file.url,
      visible: file.visible,
      created: file.created
    };

  } catch (error) {
    await transaction.rollback();
    throw {
      status: error.status || 500,
      message: error.message || 'Error al registrar el archivo',
      error: error.error || error.message
    };
  }
};